//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adres()
        {
            this.Sipariş = new HashSet<Sipariş>();
        }
    
        public int id { get; set; }
        public string başlık { get; set; }
        public string açıklama { get; set; }
        public System.DateTime ekleme_tarihi { get; set; }
        public string güncelleme_tarihi { get; set; }
        public int üye_id { get; set; }
    
        public virtual Üye Üye { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sipariş> Sipariş { get; set; }
    }
}
