//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eticaretEntities1 : DbContext
    {
        public eticaretEntities1()
            : base("name=eticaretEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<kullanıcı> kullanıcı { get; set; }
        public virtual DbSet<Mesaj> Mesaj { get; set; }
        public virtual DbSet<Sipariş> Sipariş { get; set; }
        public virtual DbSet<Sipariş_Detay> Sipariş_Detay { get; set; }
        public virtual DbSet<Ürün> Ürün { get; set; }
        public virtual DbSet<Üye> Üye { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
    }
}
