//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ürün
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ürün()
        {
            this.Sipariş_Detay = new HashSet<Sipariş_Detay>();
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int id { get; set; }
        public string ad { get; set; }
        public string açıklama { get; set; }
        public decimal fiyat { get; set; }
        public string resim { get; set; }
        public int puanlayan_üye_sayısı { get; set; }
        public bool stokta_var { get; set; }
        public int stok_sayısı { get; set; }
        public System.DateTime ekleme_tarihi { get; set; }
        public Nullable<System.DateTime> güncelleme_tarihi { get; set; }
        public int puan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sipariş_Detay> Sipariş_Detay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
